name: gridy_id_client
version: 0.5.0
description: Gridy ID Dart API client
homepage: https://gridy.io
publish_to: 'none'

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: '>=4.0.1 <5.0.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  uuid: ^3.0.7
  pointycastle: ^3.7.3

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0
